# Generated by Django 3.2.5 on 2021-11-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', '❶'), ('2', '❷'), ('3', '❸'), ('4', '❹'), ('5', '❺'), ('6', '❻'), ('7', '❻'), ('8', '❽'), ('9', '❾'), ('10', '❿')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
